import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import ContactForm from "@/components/ui/contact-form";
import SocialMediaSidebar from "@/components/ui/social-media-sidebar";
import SEO from "@/components/SEO";
import { Link } from "react-router-dom";
import {
  Filter, Shield, Snowflake, Activity, ArrowRight,
  Server, Zap, AlertTriangle, Thermometer, Droplets
} from "lucide-react";
import heroImage from "@/assets/hero-datacenter.jpg";

const DataCenter = () => {
  const solutions = [
    {
      icon: Filter,
      title: "Air Filtration Systems",
      description: "Multi-stage HEPA/ULPA filtration achieving 99.97% particle capture at 0.3µm. ISO 14644-1 Class 8 cleanroom standards and ASHRAE TC 9.9 compliance.",
      features: ["HEPA/ULPA Filters", "Multi-Stage Design", "ISO 14644-1", "Low Pressure Drop"],
      href: "/datacenter/air-filtration-systems"
    },
    {
      icon: Shield,
      title: "Chemical Filtration",
      description: "Activated carbon and chemically impregnated media systems removing H₂S, SO₂, NOₓ, and VOCs to achieve ISA G1 'Mild' corrosivity for OEM warranty compliance.",
      features: ["ISA G1 Compliance", "Multi-Gas Removal", "> 95% Efficiency", "Corrosion Monitoring"],
      href: "/datacenter/chemical-filtration"
    },
    {
      icon: Snowflake,
      title: "Precision Cooling",
      description: "CRAC/CRAH units, in-row cooling, hot/cold aisle containment, and liquid cooling solutions delivering ±1°F temperature accuracy with up to 30% energy savings.",
      features: ["CRAC/CRAH", "Containment", "Liquid Cooling", "PUE Optimization"],
      href: "/datacenter/precision-cooling"
    },
    {
      icon: Activity,
      title: "Environmental Control",
      description: "Integrated monitoring and management of temperature, humidity, air quality, and power across your facility. DCIM/BMS integration with predictive analytics.",
      features: ["DCIM Integration", "Predictive Maintenance", "AI Analytics", "99.9%+ Uptime"],
      href: "/datacenter/environmental-control"
    }
  ];

  const challenges = [
    { icon: AlertTriangle, value: "$9,000+", label: "Cost per minute of unplanned downtime" },
    { icon: Thermometer, value: "20-50 kW", label: "Heat generated by a single high-density rack" },
    { icon: Droplets, value: "70%", label: "Hardware failures linked to environmental contamination" },
    { icon: Server, value: "3-5 years", label: "Equipment life extension with proper environmental control" }
  ];

  return (
    <div className="min-h-screen">
      <SEO
        title="Data Center Environmental Solutions | Air Filtration, Cooling & Monitoring | ROS Global Solutions"
        description="Complete data center environmental solutions — air filtration, chemical filtration, precision cooling, and DCIM environmental control. ISA G1, ASHRAE TC 9.9 compliant."
        keywords="data center air filtration, precision cooling data center, chemical filtration server room, environmental monitoring data center, ISA G1, ASHRAE TC 9.9, DCIM"
        path="/datacenter"
      />
      <SocialMediaSidebar />

      {/* Hero Section */}
      <section
        className="py-16 lg:py-24 relative bg-cover bg-center bg-no-repeat"
        style={{ backgroundImage: `url(${heroImage})` }}
      >
        <div className="absolute inset-0 bg-black/60"></div>
        <div className="container mx-auto px-4 relative z-10">
          <div className="max-w-4xl mx-auto text-center text-white">
            <Badge variant="outline" className="mb-4 border-white text-white bg-white/10 backdrop-blur-sm">
              Data Center Solutions
            </Badge>
            <h1 className="text-4xl md:text-5xl font-bold mb-6 text-white">
              Protect Your Data Center Infrastructure
            </h1>
            <p className="text-xl md:text-2xl mb-8 text-white/90 leading-relaxed">
              Comprehensive environmental solutions for air quality, cooling, and monitoring —
              engineered to maximise uptime and efficiency in the world's most demanding climates.
            </p>
            <Button
              variant="cta"
              size="lg"
              onClick={() => document.getElementById('contact-form')?.scrollIntoView({ behavior: 'smooth', block: 'end' })}
            >
              Request Assessment
            </Button>
          </div>
        </div>
      </section>

      {/* The Challenge */}
      <section className="py-16 lg:py-24">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4 text-corporate-blue">
              The Data Center Environmental Challenge
            </h2>
            <p className="text-lg text-muted-foreground leading-relaxed">
              Modern data centers face an invisible enemy: airborne contamination and inefficient cooling.
              Even microscopic particles can cause short circuits, while uncontrolled humidity and corrosive gases silently destroy equipment.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 max-w-6xl mx-auto">
            {challenges.map((item, index) => (
              <Card key={index} className="text-center shadow-[var(--shadow-card)] hover:shadow-[var(--shadow-corporate)] transition-all duration-300">
                <CardContent className="p-6">
                  <div className="w-14 h-14 bg-corporate-blue rounded-full flex items-center justify-center mx-auto mb-4">
                    <item.icon className="h-7 w-7 text-white" />
                  </div>
                  <p className="text-2xl font-bold text-corporate-blue mb-1">{item.value}</p>
                  <p className="text-sm text-muted-foreground">{item.label}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Solutions — linking to product pages */}
      <section className="py-16 lg:py-24 bg-secondary/30">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4 text-corporate-blue">
              Our Data Center Solutions
            </h2>
            <p className="text-lg text-muted-foreground max-w-3xl mx-auto leading-relaxed">
              An integrated approach to data center environmental management — from the air
              entering your facility to the intelligence governing every system.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 max-w-6xl mx-auto">
            {solutions.map((solution, index) => (
              <Link key={index} to={solution.href} className="block group">
                <Card className="h-full shadow-[var(--shadow-card)] hover:shadow-[var(--shadow-corporate)] transition-all duration-300 group-hover:scale-[1.02] border-2 border-transparent group-hover:border-corporate-blue/20">
                  <CardHeader>
                    <div className="flex items-center mb-4">
                      <div className="w-12 h-12 bg-corporate-blue rounded-lg flex items-center justify-center mr-4">
                        <solution.icon className="h-6 w-6 text-white" />
                      </div>
                      <div className="flex-1">
                        <CardTitle className="text-corporate-blue text-lg">
                          {solution.title}
                        </CardTitle>
                      </div>
                      <ArrowRight className="h-5 w-5 text-corporate-blue opacity-0 group-hover:opacity-100 transition-opacity" />
                    </div>
                    <CardDescription className="text-base leading-relaxed">
                      {solution.description}
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="grid grid-cols-2 gap-2 mb-4">
                      {solution.features.map((feature, idx) => (
                        <Badge key={idx} variant="secondary" className="text-xs">
                          {feature}
                        </Badge>
                      ))}
                    </div>
                    <span className="text-sm font-medium text-corporate-blue group-hover:underline">
                      Learn More →
                    </span>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Why Choose ROS Global */}
      <section className="py-16 lg:py-24">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-corporate-blue">Why Choose ROS Global for Data Centres?</h2>
            <p className="text-muted-foreground mt-2">One partner for every environmental challenge</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {[
              { icon: Shield, title: "Integrated Approach", description: "One partner for filtration, cooling, monitoring, and control — eliminating gaps between single-discipline vendors." },
              { icon: Zap, title: "Energy Optimization", description: "PUE-focused design approach to minimise operational costs while maintaining environmental compliance." },
              { icon: Server, title: "99.9%+ Uptime Target", description: "Environmental control designed to eliminate unplanned downtime caused by temperature, humidity, or contamination events." }
            ].map((item, index) => (
              <div key={index} className="text-center p-6">
                <div className="w-16 h-16 bg-corporate-blue rounded-full flex items-center justify-center mx-auto mb-6">
                  <item.icon className="h-8 w-8 text-white" />
                </div>
                <h3 className="text-xl font-bold mb-3 text-corporate-blue">{item.title}</h3>
                <p className="text-muted-foreground">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section className="py-16 lg:py-24 bg-secondary/30">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold mb-4 text-corporate-blue">
                Take Control of Your Data Centre Environment
              </h2>
              <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                From environmental assessment to fully integrated control — our specialists will design
                the optimal solution for your facility.
              </p>
            </div>

            <div id="contact-form" className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
              <div>
                <h3 className="text-2xl font-semibold mb-6 text-corporate-blue">
                  Full-Spectrum Support
                </h3>
                <div className="space-y-4 text-muted-foreground">
                  <div className="flex items-start">
                    <div className="w-2 h-2 bg-corporate-blue rounded-full mt-2 mr-3 flex-shrink-0"></div>
                    <p><strong className="text-corporate-blue">Environmental Assessment:</strong> On-site air quality testing, thermal mapping, and contamination analysis</p>
                  </div>
                  <div className="flex items-start">
                    <div className="w-2 h-2 bg-corporate-blue rounded-full mt-2 mr-3 flex-shrink-0"></div>
                    <p><strong className="text-corporate-blue">System Design:</strong> Custom filtration, cooling, and monitoring solutions for your facility</p>
                  </div>
                  <div className="flex items-start">
                    <div className="w-2 h-2 bg-corporate-blue rounded-full mt-2 mr-3 flex-shrink-0"></div>
                    <p><strong className="text-corporate-blue">Installation & Commissioning:</strong> Professional deployment with performance verification</p>
                  </div>
                  <div className="flex items-start">
                    <div className="w-2 h-2 bg-corporate-blue rounded-full mt-2 mr-3 flex-shrink-0"></div>
                    <p><strong className="text-corporate-blue">Ongoing Support:</strong> Maintenance, filter replacement, and performance monitoring</p>
                  </div>
                </div>
              </div>

              <ContactForm
                title="Request Data Centre Assessment"
                description="Tell us about your data centre requirements and we'll design the right solution."
                defaultQueryType="datacenter"
              />
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default DataCenter;